builds:
  - id: touristdb
    binary: touristdb
    main: ./cmd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: touristdb
    name_template: 'touristdb_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - touristdb
    files:
      - README.md
    wrap_in_directory: true

changelog:
  skip: true
brews:
  - name: database-tools
    ids:
      - touristdb
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/otwartaturystyka/database-tools
    description: Tools to manage tourist database
