before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - binary: touristdb
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  skip: true
brews:
  - tap:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: "https://github.com/opentouristics/database-tools"
    description: "Tools to manage tourist database"
