before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
universal_binaries:
  - replace: true
changelog:
  skip: true
brews:
  - tap:
      owner: bartekpacia
      name: database-tools
    folder: Formula
    homepage: "https://github.com/opentouristics/database-tools"
    description: "Tools to manage tourist database"
