name: Release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release_step.outputs.upload_url }}

    steps:
      - name: Create release
        id: create_release_step
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build_release:
    runs-on: ubuntu-latest
    needs: create_release

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [arm64, amd64]

    steps:
      - name: print release upload_url
        run: echo upload_url is ${{ needs.create_release.outputs.upload_url }}

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build artifact
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make

      - name: Compress artifact
        run: tar -czf touristdb.${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz touristdb

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./touristdb.${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_name: touristdb.${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
