name: Go

on:
  push:
    tags:
      - 'v*.*.*'
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [arm64, amd64]
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make
      
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        prerelease: true
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload darwin artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./touristdb
        asset_name: touristdb
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
